### PR TITLE
Release v0.5.8

### PR DESCRIPTION
**Pull request by ephathaway**
This seems familiar...

### CODE REVIEW

**Review by jusjusjus — CHANGES_REQUESTED** [review]
Great.  Please see my PR #62

**Comment by ephathaway** [comment]
> [optional] Could you sign your commits?

Yeah, I'll start doing that.

**Review by jusjusjus — APPROVED** [review]

**Comment by ephathaway** [comment]
@mscf @damian5710 we are now requiring two approvals to merge into `master` for this repo. Would one of you be able to give this a review in the near future? If not, let us know and we will see if there is someone else who can review. Thanks!

**Review by damian5710 — APPROVED** [review]
Hey @ephathaway , changes look good and all tests are passing on my end.

We might want to revise the docstring format of some functions in order to match the rest of the docstrings in this repo but we probably want to do that in a new branch.

**Comment by ephathaway** [comment]
> We might want to revise the docstring format of some functions in order to match the rest of the docstrings in this repo

Good point. It would be good to decide on a standard format across our repos if we haven't already.

**Pull request merged**
