### PR TITLE
Release v0.5.7

### PR DESCRIPTION
**Pull request by ephathaway**

### CODE REVIEW

**Comment by jusjusjus** [comment]
See my PR #51 .

**Comment by ephathaway** [comment]
@jusjusjus thanks for adding those doc strings. What was your reason for removing the entry from the unreleased section of the changelog?

**Comment by jusjusjus** [comment]
> @jusjusjus thanks for adding those doc strings. What was your reason for removing the entry from the unreleased section of the changelog?

Well, you weren't there in the Sourcerer Sprint meeting.  The way Ian explained it, this section is empty in a release unless you actually have a feature _in the release_ that is not officially released.  In our case, this isn't the case no?

**Comment by ephathaway** [comment]
> In our case, this isn't the case no?

Yeah that's right. Just wanted to understand what we put in the unreleased section.

So we can blame Ian for making us set up a changelog ;)

**Review by jusjusjus — APPROVED** [review]
I think this is now good to go.  Thanks, @ephathaway :)

**Pull request merged**
